### ISSUE TITLE
Remote images via url

### ISSUE THREAD

**Issue by muhammadzia-se** [techdivision/import-cli-simple#149]
Hi Tim,
thanks for your valuable support. AS you said that we will upload the images directly to folder and put the images relative path in csv file. but if we have remote images then what procedure we will adopt. 

Thanks & Regards,
Zia

**Comment by wagnert** [comment]
Hi @muhammadzia-se, can you please describe what a remote image is in your case and what functionality you would expect? This will help us to understand you better and probably give you a solution.

**Comment by muhammadzia-se** [comment]
Thanks for your reply.
like, i wan to add additional images under column header "additional_images" and values should separate commas "," their i will provide multiple images with comma.
eg: http://image.cdn1.jpg,http://image.cdn2.jpg,http://image.cdn3.jpg

Thanks.

**Comment by wagnert** [comment]
Ok, i understand. Should the image be downloaded and moved to the pub/media/catalog/product/ folder or do you want them be loaded from the remote location when e. g. the catalog will be rendered? Basically the importer doesn't care about the images, it'll only set the value from the additional_images column to the database table where it belongs to. This means, if you have "http://image.cdn1.jpg,http://image.cdn2.jpg,http://image.cdn3.jpg" these value will be written to the database. Did you have a look at the Magento 2 option to set a base URL for static files in the backend? I think this is the solution for what you want to do.

**Comment by muhammadzia-se** [comment]
Thank you very much for your reply. 
Actually it is saving the urls into database. and also i set the "Base URL for User Media Files" still it is not showing the images from remote source. for your best knowledge i am attaching the screenshots.
Thanks & Regards,
Zia
![base_url](https://user-images.githubusercontent.com/24359023/38776603-aac13034-40aa-11e8-8548-e3dc2e96d202.jpg)
![images](https://user-images.githubusercontent.com/24359023/38776608-c2d302b0-40aa-11e8-9e4a-e1b1334854fe.jpg)

**Comment by wagnert** [comment]
Hi @muhammadzia-se I think, you have to configure the Base URL as you did, but only specify the relative path to the Base URL in additional_images column like `my-path/test-01.jpg,my-path/test-02.jpg` ... but i didn't test it, so this is only an assumption ;)

**Comment by muhammadzia-se** [comment]
Hi @wagnert Thank you for your reply.
you can see in attached screenshot, that i am uploading images in this way comma separated, it is storing values in the database but not showing at the frond end. 
![images](https://user-images.githubusercontent.com/24359023/38799008-4cea2ff4-4174-11e8-9cd4-be6ee6ebcb17.jpg)

**Comment by wagnert** [comment]
Hi @muhammadzia-se, please try it without the base URL in the additional_images field, only specify the relative path to the images like `my-path/test-01.jpg,my-path/test-02.jpg`.

**Comment by muhammadzia-se** [comment]
hi Wagnert,
thanks for your kind reply!
you are right that i have to give relative path. but that will only be possible if i have those images in my database. this is first time i am uploading products with remote urls, those images are present on cloud i want them to be in magento while importing.

Regards,
Zia

**Comment by wagnert** [comment]
@muhammadzia-se Hi, as described before, this should not be an importer issue, it's more up to your magento configuration and the path specified in your import files. If you need more help regard Magento image handling, please checkout the Magento developer documentation.
