### ISSUE TITLE
Support for database prefixes

### ISSUE THREAD

**Issue by kjhnns** [techdivision/import-cli-simple#216]
My database is using a prefix for the tables. I found yet no way to add a database prefix to the configuration. Is there a solution to this problem?

**Comment by wagnert** [comment]
Hi, i’m really sorry to say, but actually we don’t have support for prefixes, but we’ll add it to the feature list. Thanks for asking 🙂

**Comment by wagnert** [comment]
@kjhnns I've created the branch 3.8.x with the table prefix feature. It'll finally be released with the 3.8.0 version, but if you like and have the time you're welcome to test it. Your feedback will be well appreciated.

**Comment by wagnert** [comment]
This feature has been released with version [3.8.0](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.0).
