### ISSUE TITLE
Import Attributes using the command bin/import-cli-simple.phar import:attributes fails 

### ISSUE THREAD

**Issue by mairl** [techdivision/import-cli-simple#220]
Import Attributes using the command bin/import-cli-simple.phar import:attributes fails.
* it not possible to import an attributes-set using the bin/import-cli-simple.phar
* for this import was used the provided import-cli-simple  data

![Import error for attributes-set](https://user-images.githubusercontent.com/10232453/60434512-9630de80-9c07-11e9-9292-62c286da621f.png)
screenshot

**Comment by wagnert** [comment]
Has been fixed with [techdivision/import-cli-simple 3.5.0](https://github.com/techdivision/import-cli-simple/releases/tag/3.5.0).
