### ISSUE TITLE
Issue to load configuration using import-cli-simple.phar

### ISSUE THREAD

**Issue by mairl** [techdivision/import-cli-simple#221]
issue to load the configuration using import-cli-simple.phar for import

![Bildschirmfoto 2019-07-01 um 14 10 39](https://user-images.githubusercontent.com/10232453/60435506-0ccedb80-9c0a-11e9-8ff0-4ed00d5f1ca1.png)

**Comment by wagnert** [comment]
A [documentation page](https://docs.m2if.com/getting-started/usage/using-as-phar) that describes how this can be done has been added.
