### ISSUE TITLE
issue installing import-cli-simple using composer

### ISSUE THREAD

**Issue by mairl** [techdivision/import-cli-simple#222]
installing import-cli-simple failes because of the proper version of jms/serializer
![Bildschirmfoto 2019-07-01 um 14 10 39](https://user-images.githubusercontent.com/10232453/60438172-61755500-9c10-11e9-88cd-91378a7cce19.png)

**Comment by wagnert** [comment]
A [documentation page](https://docs.m2if.com/getting-started/usage/using-as-phar) that describes how this can be done has been added.
