### ISSUE TITLE
CSV date format import improvements

### ISSUE THREAD

**Issue by Morgy93** [techdivision/import-cli-simple#229]
Current date format is `n/d/y, g:i A`

1. With Magento it's possible to use date attributes without time, so please make it possible to import data without time given. (eg. without `, g:i A`)
![image](https://user-images.githubusercontent.com/7961978/64764264-ffa36680-d541-11e9-9b6e-b845ef348e06.png)

2. It shouldn't matter if you use like `d`or `j`, `m` or `n` (with and without leading zeros)
Magento saves the date like `YYYY-MM-DD HH:MM:SS` (2019-09-12 09:55:42) or like [date](https://www.php.net/manual/en/function.date.php) `Y-m-d H:i:s` so it would be awesome to have support for that as well.

**Comment by wagnert** [comment]
@Morgy93 Thanks for reporting. I had a more detailed look at the PHP documentation for the [\DateTime::createFromFormat()](https://www.php.net/manual/de/datetime.createfromformat.php) method we use to parse the date.

The method doesn't allow something like optional time, so it's necessary to specify the date format used in the CSV file.

But I guess, that your CSV file **ALWAYS** contains the date without time, correct? If so, you can specify the date format for the given subject like

```json
{
  ...,
  {
    "name" : "add-update",
    "plugins" : [
      "id": "import.plugin.subject",
      "subjects": [
        {
          "id": "import_product.subject.bunch",
          "identifier": "files",
          "date-converter": [
            "source-date-format": "n/d/y"
          ],
          "file-resolver": {
            "prefix": "product-import"
           },
           "observers": [ ... ]
         }
       ]
     ]
   }
}
```

Please do not forget to configure it for every operation (`add-update`, `replace`, `delete`) you want to use.

**Comment by Morgy93** [comment]
The ability to specify the date format is totally fine.
I'd just like to have a more "global" option for this.

But maybe this can be achieved with: https://feathub.com/techdivision/import-cli-simple/+2

**Comment by wagnert** [comment]
@Morgy93 All right, I'll see if it's possible to achieve this with techdivision/import-cli-simple#2
