### ISSUE TITLE
Integrity constraint violation in catalog_product update

### ISSUE THREAD

**Issue by adhocore** [techdivision/import-cli-simple#238]
```
logger/system.ERROR: SQLSTATE[23000]:
  Integrity constraint violation: 1452 Cannot add or update a child row:
  a foreign key constraint fails (`magento`.`catalog_product_entity_text`, 
  CONSTRAINT `CATALOG_PRODUCT_ENTITY_TEXT_ROW_ID_CATALOG_PRODUCT_ENTITY_ROW_ID` 
  FOREIGN KEY (`row_id`) REFERENCES `catalog_product_entity` (`row_id`) ON )
when executing SQL
```
```sql
INSERT INTO catalog_product_entity_text
    (row_id,
     attribute_id,
     store_id,
     value)
VALUES (14,
     75,
     1,
     'The new description goes here')
```
... in file `<file>.csv` on line `<line>`

Magento 2.3.3 EE and M2IF 3.8 using minimal csv file with below headers:
```
sku,product_type,attribute_set_code,store_view_code,description,color,categories
```
and two rows with all details same except `store_view_code` (varies by locale) and `description` (varies by locale too)

in first import it works fine. but with same dataset if i change the `description` and import again, there is an error as shown above.

**Comment by wagnert** [comment]
Hi @adhocore,

I've tested it with the latest 3.8.7 and I was not able to reproduce the issue. As the minimum, I've to specify the following headers (together with the example data I used)

```csv
sku,name,product_type,attribute_set_code,store_view_code,description,color,categories,is_returnable,url_key,visibility
24-MB01,Joust Seesack,simple,Default,,Deutsche Beschreibung,black,"Default Category/Gear,Default Category/Gear/Bags",1,,"Catalog, Search"
24-MB01,Joust Duffle Bag,simple,Default,en_us,United States Description,black,"Default Category/Gear,Default Category/Gear/Bags",1,,"Catalog, Search"
```

I was able to import it as many times as I wanted. I'll be very helpful to get a more detailed description that allows me to reproduce the issue.

**Comment by adhocore** [comment]
hi @wagnert it is related to my PR techdivision/import-product#148, because it picked wrong row_id hence constraint violation.

fixed by that PR already. closing

**Comment by wagnert** [comment]
@adhocore Thanks :-)
