### ISSUE TITLE
Get magento version from cli (as fallback)

### ISSUE THREAD

**Issue by Morgy93** [techdivision/import-cli-simple#239]
Hello,

if the `composer.json` lacks the `version` which is obviously needed:

```
In SimpleConfigurationLoader.php line 443:
                                                                                                                           
  Can't detect a version in "/var/www/html/composer.json", please set Magento Version with the "--magento-version" option
```

You might want to grab the version from `/bin/magento --version`:
```
$ /bin/magento --version
Magento CLI 2.3.3
```

**Comment by wagnert** [comment]
@Morgy93 Thanks for reporting, I'll take that into account for the next version :-)

**Comment by wagnert** [comment]
Hi @Morgy93, we've refactored the version check from `composer.json` to `composer.lock` and checking for version by evaluating the version of the installed `magento/product-community|enterprise-edition`. The related issue is techdivision/import-cli-simple#250. Would you please check if the implementation is now still o. k. for you, so we can close the issue as soon as possible.

**Comment by Morgy93** [comment]
Much better, thanks!

Closing~
