### ISSUE TITLE
Error on create:configuration-file

### ISSUE THREAD

**Issue by fheider** [techdivision/import-cli-simple#242]
**Describe the bug**
bin/import-simple import:create:configuration-file
PHP Fatal error:  Uncaught Error: Call to undefined method TechDivision\Import\Configuration\Jms\Configuration::getCustom() in import-cli-simple/vendor/techdivision/import-cli/src/Command/ImportCreateConfigurationFileCommand.php:84

**To Reproduce**
1. composer create-project techdivision/import-cli-simple --no-dev
2. bin/import-simple import:create:configuration-file
3. error

**Context **
 - PHP 7.3
- techdivision/import 15.2.1
- techdivision/import-cli 9.0.4

**Comment by wagnert** [comment]
@fheider I've added it to the backlog and we'll fix the issue with the next release. Thanks for reporting!

**Comment by wagnert** [comment]
Hi @fheider I've added a bugfix to the 3.8.x branch. So if you checkout and install the latest 3.8.x branch with

git clone https://github.com/techdivision/import-cli-simple.git \
  && cd import-cli-simple \
  && git checkout 3.8.x
  && composer install 
you'll be able to test it.

The bugfix will be part of the upcoming 3.8.12 release.
