### ISSUE TITLE
Clean-up Not Happening On Product Import For Attribute Values

### ISSUE THREAD

**Issue by HarmonyR** [techdivision/import-cli-simple#243]
**Describe the bug**
According to https://docs.m2if.com/38/getting-started/configuration/clean-up:

> Clean-Up functionality for the product import is activated by default and available for ... as well as for all product attributes (clean-up-empty-columns).

The way this reads, I should not have to do anything special to remove product attribute values. However, when I unset the CSV values, the product attribute value is not unset after the product import. It seems to be ignored. I have tested this with various attribute types including dropdowns, multiple selects, and text. The values are not unset regardless of the attribute type.

**To Reproduce**
1. In Magento, create a few attributes of different types: dropdown, multiple select, text.
2. Create a new product and set values for the product attributes.
3. Create a CSV with a column for each of these attributes (not using the additional_attributes field).
4. Do not set the values for these columns in the CSV.
5. Run the product import through CLI.

**Expected behavior**
I expected the product attribute values to be removed (unset) for the given product.

**Environment**
- Magento Open Source 2.3.3
- PHP 7.3
- techdivision/import-cli-simple 3.8.11

**Comment by wagnert** [comment]
@HarmonyR We'll verify this and come back to you as soon as possible.

**Comment by wagnert** [comment]
Hi @HarmonyR, besides a bug, the documentation was wrong and I've [updated](https://docs.m2if.com/38/getting-started/configuration/clean-up) it. So if you want to *clean-up* empty columns, you've to add them to the `clean-up-empty-columns` like `"clean-up-empty-columns": [ "activity", "erin_recommends" ]`.
 
I've added the bugfix to the 3.8.x branch. So if you checkout and install the latest 3.8.x branch with

git clone https://github.com/techdivision/import-cli-simple.git \
  && cd import-cli-simple \
  && git checkout 3.8.x
  && composer install 
you'll be able to test it.

The bugfix will be part of the upcoming 3.8.12 release.
