### ISSUE TITLE
Issues with convert in 3.8.11

### ISSUE THREAD

**Issue by HarmonyR** [techdivision/import-cli-simple#244]
**Describe the bug**
I cannot find documentation anywhere on how to use the convert shortcut for attributes, https://docs.m2if.com/38/getting-started/usage#shortcuts. I tried the following.

`vendor/bin/import-simple import:create:ok-file && vendor/bin/import-simple import:attributes -- convert`

And received this error: **Can't find any plugins for shortcut "convert"**

I installed through composer, so I have all the libraries. What am I missing?

What I am actually trying to do is get it to generate an attribute template file for me. Then I can start filling in the rest of the information.

**To Reproduce**
1. Upload a product import CSV.
2. Run the following command.
`vendor/bin/import-simple import:create:ok-file && vendor/bin/import-simple import:attributes -- convert`

**Expected behavior**
I expected an attribute CSV to be generated.

**Environment**
- Magento Open Source 2.3.3
- PHP 7.3
- techdivision/import-cli-simple 3.8.11

**Comment by wagnert** [comment]
@HarmonyR Thanks for reporting. In general, you're absolutely right. There is actually no shortcut defined for the `convert` operation on attributes. I'll add this to the upcoming version 3.8.12. When I understand you right, what you expect to do is to generate a template CSV file, right? This will no be the behaviour, because the `convert` shortcut will expect a CSV file with products and will create/convert the missing attribute options into a CSV file that can be imported. But you're more looking for something like a stub generator, right?

**Comment by HarmonyR** [comment]
Hi @wagnert, thank you for getting back to me. I expect an attribute_import CSV to be created from the provided product_import CSV. That is what the current documentation implies the outcome will be.

> Extracts the attributes or categories from a given CSV files with products (available for ATTRIBUTES and CATEGORIES)

A template of the attribute_import CSV would be very helpful (since there are so many fields involved). However, we can make one ourselves from the fields listed at https://docs.m2if.com/38/file-structure/attributes.

**Comment by wagnert** [comment]
@HarmonyR All right, so you'll receive this with the upcoming version :) Regarding the template, I'll be nice if you would create a feature request (via the template), so we can go a bit deeper into the details, e. g. if there should be some sample lines and what the default values should/could be :)

**Comment by wagnert** [comment]
Hi @HarmonyR I've added the requested functionality to the 3.8.x branch. So if you checkout and install the latest 3.8.x branch with

```sh
git clone https://github.com/techdivision/import-cli-simple.git \
  && cd import-cli-simple \
  && git checkout 3.8.x
  && composer install 
```

you'll be able to test it. 

I've added the missing `convert` shortcuts for attributes and categories. Please keep in mind, that CSV files will only be generated, if at least one attribute option or category, that is referenced in the product CSV file, is **NOT** available in the database.
