### ISSUE TITLE
Importing additional attributes in specific fields fails

### ISSUE THREAD

**Issue by Giuliano69** [techdivision/import-cli-simple#247]
**Describe the bug**
Creating a csv file with additional attributes each on specific coloumn, makes m2if import fails

**To Reproduce**
1. Created one  CSV, and validate it with Magento2 import validation 
https://drive.google.com/file/d/1s2Phz17y__V_omecN57581myjoaOks1o/view?usp=sharing
2. copy the csv file in m2root/var/importexport
3. create the ok file with m2if  and then import products
4. try to import the csv file, but the program claims it is not possible

**Expected behavior**
the file shoud be imported as in Magento2 import

**Screenshots**
https://drive.google.com/open?id=1DtbZyfMqsUHCcry6Dp2K_yZQZvyEI_Zz

**Desktop (please complete the following information):**
I’m using ubuntu 18.04 + PHP 7,2 + Apache2 + M2IF phar v3,8,0 + Magento 2.3.5p1

command sequence

**giuliano@firenze:/var/www/penstore$ bin/import-cli-simple.phar import:create:ok-file**
 ```
_______        _     _____  _       _     _
|__   __|      | |   |  __ \(_)     (_)   (_)
   | | ___  ___| |__ | |  | |___   ___ ___ _  ___  _ __
   | |/ _ \/ __| '_ \| |  | | \ \ / / / __| |/ _ \| '_ \
   | |  __/ (__| | | | |__| | |\ V /| \__ \ | (_) | | | |
   |_|\___|\___|_| |_|_____/|_| \_/ |_|___/_|\___/|_| |_|

 Now start import with serial 1235d2da-1c57-441f-aa7d-2a6e21db68c7 [none => create-ok-files] 
+--------------------------------+-------+----------------------------------------------------------------------------------+
| Variable                       | Value | Description                                                                      |
+--------------------------------+-------+----------------------------------------------------------------------------------+
| innodb_flush_log_at_trx_commit | 1     | Your setting for may result in a significantly slower performance. Consider to s |
|                                |       | witch this value to 0 or 2 to improve performance. Read more about that topic on |
|                                |       | the MySQL website https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html |
|                                |       | #sysvar_innodb_flush_log_at_trx_commit.                                          |
+--------------------------------+-------+----------------------------------------------------------------------------------+
 Successfully executed command import:create:ok-file with serial 1235d2da-1c57-441f-aa7d-2a6e21db68c7 in 00:00:00 s 

```
**giuliano@firenze:/var/www/penstore/var/importexport$ ls -al**
```
totale 12
drwxrwsrwx  2 www-data www-data   71 mag  8 15:27 .
drwxrwsrwx 12 www-data www-data  336 mag  8 15:28 ..
-rw-r--r--  1 giuliano www-data 2864 mag  7 21:34 magento_bag_3.csv
-rw-r--r--  1 giuliano www-data   17 mag  8 15:27 magento_bag.ok
-rw-r--r--  1 giuliano www-data  809 mag  8 15:27 system.log

```

**giuliano@firenze:/var/www/penstore$ bin/import-cli-simple.phar import:products** 
 ```
_______        _     _____  _       _     _
|__   __|      | |   |  __ \(_)     (_)   (_)
   | | ___  ___| |__ | |  | |___   ___ ___ _  ___  _ __
   | |/ _ \/ __| '_ \| |  | | \ \ / / / __| |/ _ \| '_ \
   | |  __/ (__| | | | |__| | |\ V /| \__ \ | (_) | | | |
   |_|\___|\___|_| |_|_____/|_| \_/ |_|___/_|\___/|_| |_|

 Now start import with serial 230a2cc8-a532-40d0-92b9-5bc21385ec48 [catalog_product => add-update] 
+--------------------------------+-------+----------------------------------------------------------------------------------+
| Variable                       | Value | Description                                                                      |
+--------------------------------+-------+----------------------------------------------------------------------------------+
| innodb_flush_log_at_trx_commit | 1     | Your setting for may result in a significantly slower performance. Consider to s |
|                                |       | witch this value to 0 or 2 to improve performance. Read more about that topic on |
|                                |       | the MySQL website https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html |
|                                |       | #sysvar_innodb_flush_log_at_trx_commit.                                          |
+--------------------------------+-------+----------------------------------------------------------------------------------+
 Stop processing, because can't find the mandatory OK file to process at least one of 1 files 

```

**Comment by Giuliano69** [comment]
The system.log file in case it can help

https://drive.google.com/file/d/1hz1NsruILauNTh_PR9rDH7_MK3cbw9jo/view?usp=sharing

**Comment by wagnert** [comment]
@Giuliano69 I had a look at your file found two things you've to change:

* The filename has to follow a special convention to make M2IF recognize it (read more about that topic in the [documentation](https://docs.m2if.com/38/getting-started/usage) or one of our older blog [posts](https://m2if.com/blog/sample-data-import)), in your case simply rename it from `magento_bag_3.csv` to `product-import_20200509-110829_01.csv` for example
* The second thing was an invalid datetime in the column `special_price_from_date`, which I fixed to to `5/6/20, 10:13 PM`

After that, I was able to import your file [product-import_20200509-110829_01.csv.zip](https://github.com/techdivision/import-cli-simple/files/4603094/product-import_20200509-110829_01.csv.zip) without problems.

Regarding the message with the `innodb_flush_log_at_trx_commit` MySQL setting, I recommend having a look in our Pacemaker [documentation](https://docs.met.tdintern.de/pacemaker/1.3/faq.html#the-performance-on-the-productionstating-system-is-worse-than-on-my-local-machine). But in short, changing the database setting from `1` to `2` will have a significant performance impact.

If you ask yourself, WTF is Pacemaker and why should I read the documentation, I can give you the information, that we'll soon rename M2IF to Pacemaker and we also have a commercial version of Pacemaker that has extended functionality and improved performance (which will be handy, when you've to import a large amount of SKUs probably).

Hope that helps to solve your issue. Do not hesitate to contact us, if you need any further assistance.

**Comment by wagnert** [comment]
@Giuliano69 Has this issue been resolved, or can we close it?

**Comment by Giuliano69** [comment]
Thanks Tim for your kind reply.
I will try asap the import with the corrected filename. Sorry for the error.
The "Successfully executed" message may me feel I had no mistakes, but indeed I hat some .. :-)

One important question about your ADVICE for **innodb_flush_log_at_trx_commit** MySQL setting.

AFAIK, Default value of innodb_flush_log_at_trx_commit is set to 1 because it is required for ACID compliance. 
Changing this value can increase performance, but could expose the system in case of crash to a loss of data, non only during import but also during normal activity DB operations  

Considering your client portfolio (paceMaker) and the HUGE experience I would like to ask you:

1. Did you ever encounter some kind of  data loss/corruption moving to value 2, even if with particular  configuration ?
2. Does the benefit for this change show ONLY  to SQL-DML operation like m2id (i.e update/import of products) , or it can ALSO be noticed during DAILYl store-front activity (i.e  SQL-DQL for dynamic user navigation  of the site) ?

**Comment by wagnert** [comment]
Hi @Giuliano69 I want to answer your questions:

1. No, we did not have any problems with setting the value to 2 yet
2. It can have a significant effect on write operations (which has a massive performance improvement for M2IF), but from our point of view, we did not notice any effect on the store-front activity as this will mostly use read operations

Hope that answers your question, but you should keep in mind, that this works for us and our projects, depending on your requirements you have to consider if data security may become more important.
