### ISSUE TITLE
Still trying to parse composer,json for Magento edition, even we have a configuration file

### ISSUE THREAD

**Issue by amenk** [techdivision/import-cli-simple#250]
**Describe the bug**

We try to call import-simple with as small parameters as possible. But it seems to parse the composer.json even magento edition is specified

Is it a normal practice to have the Magento Edition in the composer JSON and not the own customer's project?

**To Reproduce**

composer.json starts like this:

	{
	    "name": "imi/custom_name_shop",
	    "description": "Customer Shop",
	    "type": "project",

app/etc/configuration/configuration.json

	{
	    "magento-edition": "CE",
	    "magento-version": "2.3.4",
	    "operation-name" : "replace",
	    "table-prefix": ""
	}

Run the script

	amk@lafto:~/imi/projects/shop.example.com$ vendor/bin/import-simple import:create:ok-file

	In SimpleConfigurationLoader.php line 435:
		                                                                                                                                                                           
	  "shop_example_com" detected in "/home/amk/imi/projects/shop.example.com/composer.json" is not a valid Magento Edition, please set Magento Edition with the "--magento-edition" option  
		                                                                                                                                                                           

**Expected behavior**
It uses the edition from the config file

**Comment by amenk** [comment]
I think there seem to be two problems:

* Magento composer version check by M2IF is still done even if it is configured in the configuration.json
* M2IF checks the composer.json root version but should actually check magento/product-community-edition's version in composer.lock

**Comment by wagnert** [comment]
@amenk Thanks for reporting. We'll check this as soon as possible. As a quickfix, it should be possible to override Magento edition + version on commandline with `--magento-edition=CE` and `--magento-version=2.3.5`.

**Comment by amenk** [comment]
Yes that works, but is somehow unsatisfying. In the end of the day that is a low priority issue.

**Comment by wagnert** [comment]
@amenk All right, I'll check this as soon as possible :)

**Comment by amenk** [comment]
not yet released I think :) https://packagist.org/packages/techdivision/import-cli-simple shows 3.8.23

**Comment by wagnert** [comment]
@amenk Has been released with the [3.8.24](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.24) today.

**Comment by amenk** [comment]
thank you, I updated and was able to rename the project back to the customer name
