### ISSUE TITLE
Composer updates to wrong version

### ISSUE THREAD

**Issue by HarmonyR** [techdivision/import-cli-simple#251]
**Describe the bug**
When composer update is run, the wrong version is assumed to be the latest version. 3.18.17 is selected when the version (as of today) should be 3.8.21.

I believe the tag on https://github.com/techdivision/import-cli-simple/releases for 3.8.17 needs to be corrected (changed from 3.18.17 to 3.8.17).

**To Reproduce**
1. In a terminal run either of the following.
    a. composer require techdivision/import-cli-simple
    b. composer update --with-dependencies techdivision/import-cli-simple
2. Notice the package is updated to the wrong version.

**Expected behavior**
Package should have been updated to 3.8.21.

**Comment by wagnert** [comment]
Hm, strange ... I‘ll check this tomorrow. May you have another dependency that prevents from updating to the latest version? Did you try it on a fresh instance? Thanks for reporting @HarmonyR  🙂

**Comment by HarmonyR** [comment]
Even if you try it on a fresh install, it will try to install 3.18.17 because that looks like the highest version.

**Comment by wagnert** [comment]
Thanks for reporting, @HarmonyR. I've removed the tag and works now.
