### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'

### ISSUE THREAD

**Issue by HarmonyR** [techdivision/import-cli-simple#252]
**Describe the bug**
When importing product CSV containing a mix of new and existing products, I continue to get the following error on new products. I have confirmed the request path does not exist in the url_rewrite table.

`Integrity constraint violation: 1062 Duplicate entry for key 'URL_REWRITE_REQUEST_PATH_STORE_ID' when executing SQL "INSERT`

If I delete all products in Magento and then run the product import, I do not receive this error.

**To Reproduce**
1. Upload product CSV.
2. Run `vendor/bin/import-simple import:create:ok-file && vendor/bin/import-simple import:products`.
3. See error

**Environment**
Magento 2.3.3 CE
PHP 7.3
techdivision/import-cli-simple 3.8.21

**Comment by wagnert** [comment]
Hi @HarmonyR, thanks for reporting. Will you be able provide a CSV file with the categories, attributes and the attribute-sets also? This will make reproduction much easier :-)

**Comment by HarmonyR** [comment]
Hi @wagnert, see attached.

[url_rewrite_issue_supporting_imports.zip](https://github.com/techdivision/import-cli-simple/files/4793283/url_rewrite_issue_supporting_imports.zip)

**Comment by wagnert** [comment]
Hi @HarmonyR I've tried to reproduce the issue, but I'm not able to. I can run the import as many times as I want, but the error wasn't triggered. We are aware of such problems, which result in general out of the fact, that there is no foreign key between `catalog_product_entity.entity_id` and `url_rewrite.entity_id` which can result in some garbage in table `url_rewrite`, e. g. broken imports or manual deleting of entities via MySQL console. 

It would be very helpful, if you can clean-up the `url_rewrite` table (**ATTENTION**: Only on a test or development system) and try the import again. Additionally, it'll be helpful, if you can post a screenshot of your product SEO configuration like

![product SEO configuration](https://user-images.githubusercontent.com/287509/85395530-99c42080-b550-11ea-984a-7114d1f17d86.png)

Maybe I've a different configuration and this may cause the issue.

**Comment by wagnert** [comment]
@HarmonyR is this issue still available or are you able to import the data meanwhile? :-)

**Comment by HarmonyR** [comment]
@wagnert My settings are the same as your screenshot.

I am running Pacemaker - Community Console Tool 3.8.24 and this issue is no longer happening. Also, I am not including url_key in the "clean-up-empty-columns" list in app/etc/configuration/operations.json.

I think we can close this issue. Thanks!

**Comment by wagnert** [comment]
@HarmonyR Perfect, thanks for the update :)

**Comment by HarmonyR** [comment]
@wagnert The issue started happening again. I cannot dump the url_rewrites table because the site is live now. I will send you the log files through Slack.
