### ISSUE TITLE
Integrity constraint violation: 1048 Column 'sku' cannot be null

### ISSUE THREAD

**Issue by HarmonyR** [techdivision/import-cli-simple#253]
**Describe the bug**
When importing a CSV containing configurable products, I continue to get the following error. I have confirmed sku is being set in the CSV file.

`Integrity constraint violation: 1048 Column 'sku' cannot be null when executing SQL "INSERT
               INTO inventory_source_item
                    (source_code,
                     sku,
                     quantity,
                     status)
             VALUES (default,
                     ,
                     0,
                     1)" in file inventory-msi_20200616-000000_04.csv on line 2
`

Shouldn't the inventory be skipped for configurable products since inventory is maintained on the simples instead?

**To Reproduce**
1. Upload product CSV.
2. Run `vendor/bin/import-simple import:create:ok-file && vendor/bin/import-simple import:products`.
3. See error

**Expected behavior**
I expected inventory to be skipped for configurable products. If a record is needed, I expected the sku from the CSV to be used.

**Environment**
Magento 2.3.3 CE
PHP 7.3
techdivision/import-cli-simple 3.8.21

**Comment by HarmonyR** [comment]
Hi @wagnert, I ran a very simple CSV with only 2 configurable products and confirmed there were no hidden characters in the beginning of the file. When I ran the import, I get a new error message, but still about SKUs.

`Found not mapped entity ID for SKU  in file variants_20200616-000000_03.csv on line 2 in column(s) variant_parent_sku`

A record is being created in catalog_product_entity, but it is missing a sku. Some debugging shows the Lexer is picking up the skus from the CSV.

`TechDivision\Import\Adapter\Goodby\Lexer::parse (117) line = array (
  0 => 'sku',
  1 => 'product_type',
  2 => 'product_websites',
  3 => 'gift_message_available',
  4 => 'product_online',
  5 => 'visibility',
  6 => 'tax_class_name',
  7 => 'is_in_stock',
  8 => 'name',
  9 => 'attribute_set_code',
  10 => 'categories',
  11 => 'configurable_variations',
)
TechDivision\Import\Adapter\Goodby\Lexer::parse (117) line = array (
  0 => 'HR-TEST-04',
  1 => 'configurable',
  2 => 'base',
  3 => '2',
  4 => '1',
  5 => 'Catalog, Search',
  6 => 'Taxable Goods',
  7 => '1',
  8 => 'HR Configurable Test Product 04',
  9 => 'Default',
  10 => 'SHOP/KC Gear/KC Apparel',
  11 => 'sku=72021,pim_lenscolor=|sku=72011,pim_lenscolor=',
)
`
I traced the rows through TechDivision\Import\Adapter\Goodby\Interpreter::interpret and confirmed the sku is still in the data before and after notify(). This is called repeatedly. It appears once the variant process/subject is entered, that is when the sku goes missing.

`TechDivision\Import\Product\Variant\Observers\VariantSuperLinkObserver::process (80) ColumnKeys::VARIANT_PARENT_SKU=variant_parent_sku, parentSku =''

vendor/techdivision/import-product-variant/src/Observers/VariantSuperLinkObserver.php(87): TechDivision\Import\Product\Variant\Observers\VariantSuperLinkObserver->mapSku(NULL)`

**Comment by wagnert** [comment]
Ok @HarmonyR, this is for sure a different problem, so I'll create a new issue [techdivision/import-cli-simple#254](https://github.com/techdivision/import-cli-simple/issues/254) for it and close this one for completeness, o. k.?
