### ISSUE TITLE
Make console output colorful

### ISSUE THREAD

**Issue by amenk** [techdivision/import-cli-simple#255]
**Is your feature request related to a problem? Please describe.**

In the past we had an own function to display colorful log messages on the console.
No the logging output is sent to the console (4.0-alpha1) per default, which is great.

Shall we make that log output also use colors as per log level?

**Describe the solution you'd like**

wrap the messages with <warning>...</warning> and so on

**Describe alternatives you've considered**
Leave it colorless

We might make a pull request, if you agree that the feature is desirable

**Comment by pathmissing** [comment]
Hi @amenk, thank you for the suggestion. Would definitely be a useful addition :)
Do you have any specific ideas as to how and what you want to color?
Or do you have a screenshot with what you think the console output should look like?
Thanks!

**Comment by amenk** [comment]
Just depending on the log level. There are already <warning> tags for the console I think

**Comment by pathmissing** [comment]
Alright, sounds good. We are always happy for any contributions :)

**Comment by amenk** [comment]
https://symfony.com/doc/current/logging/monolog_console.html states that output should be already colored.

But there is also https://github.com/bramus/monolog-colored-line-formatter - not sure if that is needed and if we want to introduce a dependency just for this.

**Comment by amenk** [comment]
Looks like for the first solution we would need also an additional package: https://github.com/symfony/monolog-bridge

**Comment by amenk** [comment]
I thought it would work in a different way.
Please advise if we would like to require one more package.
We can as well close this otherwise, it's not very important.

**Comment by amenk** [comment]
I will go now with this:

https://stackoverflow.com/a/24086468/288568
