### ISSUE TITLE
Extension Libraries configuration is not parsing 

### ISSUE THREAD

**Issue by c-schwan** [techdivision/import-cli-simple#256]
if the custom configuration has included extension-lib the etc folder with configuration files will not be merged with the rest of it.

The File TechDivision\Import\Configuration\Jms\Parsers\JsonParser will parse only the config files when using additional-vendor-dirs configutation

**Comment by wagnert** [comment]
Hi @c-schwan, seems that this has not yet been implemented, actually only parsing of the Symfony DI configuration of extension libraries has been supported. We'll add this functionality with the upcoming release 3.8.34.

**Comment by wagnert** [comment]
@c-schwan Can you please confirm that the feature works as expected? Thank you, your support is well appreciated.

**Comment by wagnert** [comment]
Has been added with [3.8.34](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.34).
