### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()

### ISSUE THREAD

**Issue by roman204** [techdivision/import-cli-simple#271]
**Describe the bug**
Import command (with command) is not working because of the missing method.
After some investigation i found out that the doctrine method was deprecated as mentioned here https://github.com/doctrine/annotations/commit/17e4de92d524d47120fc747292b147030faccf54 

**To Reproduce**
1. run ./vendor/bin/import-simple import:create:ok-file

**Expected behavior**

**System**
PHP8.1 with M 2.4.5-p1.

**Stacktrace**
www-data@e2ef0ff6eb9c:~/htdocs$ ./vendor/bin/import-simple import:create:ok-file
PHP Fatal error:  Uncaught Error: Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() in /var/www/htdocs/vendor/techdivision/import-configuration-jms/src/ConfigurationFactory.php:120
Stack trace:
#0 [internal function]: TechDivision\Import\Configuration\Jms\ConfigurationFactory->__construct(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(TechDivision\Import\Configuration\Jms\ConfigurationParserFactory), Object(JMS\Serializer\SerializerBuilder))
#1 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1109): ReflectionClass->newInstanceArgs(Array)
#2 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'import_cli.conf...')
#3 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1232): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('import_cli.conf...', 1, Array, true)
#4 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1180): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, true)
#5 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1078): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#6 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'import_cli.conf...')
#7 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1232): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('import_cli.conf...', 1, Array, true)
#8 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1082): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, true)
#9 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'configuration')
#10 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(553): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('configuration', 1)
#11 /var/www/htdocs/vendor/techdivision/import-cli/src/Command/AbstractImportCommand.php(108): Symfony\Component\DependencyInjection\ContainerBuilder->get('configuration')
#12 /var/www/htdocs/vendor/symfony/console/Command/Command.php(255): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/htdocs/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/htdocs/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportCreateOkFileCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/htdocs/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/htdocs/vendor/techdivision/import-cli-simple/bootstrap.php(40): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/htdocs/vendor/techdivision/import-cli-simple/bin/import-simple.php(48): require('/var/www/htdocs...')
#18 /var/www/htdocs/vendor/techdivision/import-cli-simple/bin/import-simple(2): require('/var/www/htdocs...')
#19 /var/www/htdocs/vendor/bin/import-simple(117): include('/var/www/htdocs...')
#20 {main}
  thrown in /var/www/htdocs/vendor/techdivision/import-configuration-jms/src/ConfigurationFactory.php on line 120

Fatal error: Uncaught Error: Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() in /var/www/htdocs/vendor/techdivision/import-configuration-jms/src/ConfigurationFactory.php:120
Stack trace:
#0 [internal function]: TechDivision\Import\Configuration\Jms\ConfigurationFactory->__construct(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(TechDivision\Import\Configuration\Jms\ConfigurationParserFactory), Object(JMS\Serializer\SerializerBuilder))
#1 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1109): ReflectionClass->newInstanceArgs(Array)
#2 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'import_cli.conf...')
#3 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1232): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('import_cli.conf...', 1, Array, true)
#4 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1180): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, true)
#5 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1078): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#6 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'import_cli.conf...')
#7 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1232): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('import_cli.conf...', 1, Array, true)
#8 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(1082): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, true)
#9 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(608): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'configuration')
#10 /var/www/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(553): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('configuration', 1)
#11 /var/www/htdocs/vendor/techdivision/import-cli/src/Command/AbstractImportCommand.php(108): Symfony\Component\DependencyInjection\ContainerBuilder->get('configuration')
#12 /var/www/htdocs/vendor/symfony/console/Command/Command.php(255): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/htdocs/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/htdocs/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportCreateOkFileCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/htdocs/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/htdocs/vendor/techdivision/import-cli-simple/bootstrap.php(40): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/htdocs/vendor/techdivision/import-cli-simple/bin/import-simple.php(48): require('/var/www/htdocs...')
#18 /var/www/htdocs/vendor/techdivision/import-cli-simple/bin/import-simple(2): require('/var/www/htdocs...')
#19 /var/www/htdocs/vendor/bin/import-simple(117): include('/var/www/htdocs...')
#20 {main}
  thrown in /var/www/htdocs/vendor/techdivision/import-configuration-jms/src/ConfigurationFactory.php on line 120

**Comment by Mardl** [comment]
https://github.com/techdivision/import-configuration-jms/issues/48
